#!/usr/bin/env bash
# Install and configure Nginx server (in remote server).

# Update apt-get (first time use) and Install Nginx
sudo apt-get -y update
sudo apt-get -y install nginx
# reconfigure firewall to allow access to the nginx service
sudo ufw allow 'Nginx HTTP'

# configure (use defaults), just replace index.html's contents
echo "Hello World!" | sudo tee /var/www/html/index.html
# once done, restart nginx to enable the changes
sudo service nginx restart
