#!/usr/bin/env bash
# Install and configure Nginx server (in remote server).

sudo apt-get -y update
sudo apt-get -y install nginx

# reconfigure firewall to allow access to the nginx service
sudo ufw allow 'Nginx HTTP'

echo "Hello World!" | sudo tee /var/www/html/index.html

sudo service nginx restart
