#!/usr/bin/env bash
#Server configuration and add headers

sudo apt -y update

sudo apt -y install nginx

mkdir /etc/nginx/html
touch /etc/nginx/html/index.html
echo "Hello World!" > /etc/nginx/html/index.html

touch /etc/nginx/html/404.html
echo "Ceci n'est pas une page" > /etc/nginx/html/404.html

printf %s "server {
        listen 80 default_server;
        listen [::]:80 default_server;
        add_header X-Served-By $hostname;

        rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;
        root /var/www/html;

        index index.html index.htm index.nginx-debian.html;

        error_page 404 /404.html;
        server_name _;

        location / {
                # First attempt to serve request as file, then
                # as directory, then fall back to displaying a 404.
                try_files $uri $uri/ @404;
        }
}" > /etc/nginx/sites-available/default

sudo service nginx restart
