#!/usr/bin/env bash
# Script ensures that Nginx is installed, configured to listen on port 80.
sudo apt-get update
sudo apt-get install -y nginx
sed -i 's/listen 80 default_server;/listen 80 default_server;/' /etc/nginx/sites-available/default
sudo service nginx restart
