#!/usr/bin/env bash
#Kill a process using the SIGKILL (9) signal,
#SIGKILL(9) Forcefully terminates a process without giving it a chance to clean up resources.

pid=$(pgrep -f "7-highlander")
if [ -n "$pid" ]; then
    kill -9 "$pid"
fi
