#!/usr/bin/env bash
# Displays Best School x10 and hi before last.

sentence="Best School"
i=0

while [ $i -lt 10 ]; do
  echo "$sentence"
  if [ $i -eq 8 ]; then  #
    echo "Hi"
  fi
  i=$((i+1))
done

