#!/usr/bin/env bash
#Configures a container so that nginx runs as 'nginx' user & listens on all active IPs on port 8080

sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
chmod 644 /etc/nginx/nginx.conf
sudo -u nginx service nginx start
